version: 2.1

workflows:
  test-deploy:
    jobs:
      - build
      - test
      - deploy
jobs:
  build:
    docker: 
      - image: cimg/node:14.13.0
      steps:
        - checkout
        - run:
            name: Run Build Command
            command: echo "Hello I am building."
  test:
    docker:
      - image: cimg/node:14.13.0
      steps:
        - checkout
        - run:
            name: Run Tests
            command: echo "Hello I am testing"
  deploy:
    docker:
      - image: cimg/node:14.13.0
      steps:
        - checkout
        - run:
            name: Run Deploy Command
            command: echo "Hello I am deploying"

